# Generated by Django 5.1.4 on 2026-05-26 15:24

import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(blank=True, choices=[('fnb', 'FNB Eswatini'), ('standard', 'Standard Bank'), ('nedbank', 'Nedbank'), ('eswatini_bank', 'Eswatini Bank')], max_length=100)),
                ('default_funding_mode', models.CharField(choices=[('credit', 'Qinance Credit Card'), ('bank', 'Bank Account (EPS)'), ('jit', 'JIT Bank to Card')], default='credit', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=24.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('kyc_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ctr', 'Cash Transaction Report'), ('str', 'Suspicious Transaction Report')], max_length=10)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('flag_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_submission', 'Pending Submission'), ('submitted', 'Submitted to FIU'), ('acknowledged', 'Acknowledged by FIU')], default='pending_submission', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed — Unpaid'), ('paid_minimum', 'Minimum Paid'), ('paid_full', 'Paid in Full'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='payments.customer')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(default=payments.models.generate_card_number, max_length=16)),
                ('cvv', models.CharField(default=payments.models.generate_cvv, max_length=64)),
                ('expiry_date', models.DateField(default=payments.models.default_expiry)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('pending', 'Pending Activation')], default='active', max_length=20)),
                ('bin_country', models.CharField(default='ZA', max_length=50)),
                ('card_network', models.CharField(default='Visa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DebitMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('fnb', 'FNB Eswatini'), ('standard', 'Standard Bank'), ('nedbank', 'Nedbank'), ('eswatini_bank', 'Eswatini Bank')], max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('authorised_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='payments.customer')),
            ],
            options={
                'ordering': ['-authorised_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('cashback', 'Cash Back — Bank to Cash'), ('bank_deposit', 'Bank Deposit — Cash to Bank')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('merchant_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_transactions', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_transactions', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cashback_enabled', models.BooleanField(default=False)),
                ('is_bank_deposit_enabled', models.BooleanField(default=False)),
                ('available_cash_float', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_cashback_limit', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('total_cashback_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration'), ('tax_clearance', 'Tax Clearance Certificate'), ('bank_letter', 'Bank Confirmation Letter'), ('id_owner', 'Owner ID / Passport'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='merchant_kyc/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for Customer'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('funding_mode', models.CharField(blank=True, choices=[('credit', 'Qinance Credit Card'), ('bank', 'Bank Transfer (EPS)'), ('jit', 'JIT Bank to Card')], max_length=30)),
                ('bank_used', models.CharField(blank=True, max_length=100)),
                ('jit_funded', models.BooleanField(default=False)),
                ('jit_bank', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('repayment', 'Repayment'), ('interest', 'Interest Charge'), ('fee', 'Fee'), ('refund', 'Refund')], max_length=20)),
                ('funding_mode', models.CharField(blank=True, choices=[('credit', 'Qinance Credit'), ('bank', 'Bank Transfer (EPS)'), ('jit', 'JIT Bank to Card')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.creditstatement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='payments.customer')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.merchant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.paymentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('eps_transfer', 'EPS Bank Transfer'), ('debit_order', 'Debit Order'), ('cash', 'Cash at Branch')], default='eps_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payments.customer')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='payments.creditstatement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
