# Generated by Django 5.1.4 on 2026-05-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_regulatoryreport'),
        ('payments', '0004_agent_banking'),
    ]

    operations = [
    ]
