# Generated by Django 5.1.4 on 2026-06-27 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdevicesecret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerdevicesecret',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingsettlement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingsettlement',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pendingsettlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — awaiting settlement window'), ('settled', 'Settled — EPS executed'), ('cancelled', 'Cancelled — lost conflict resolution'), ('reversed', 'Reversed — EPS failed')], default='pending', max_length=20),
        ),
    ]
