# Generated by Django 5.1.4 on 2026-06-30 19:51

import django.db.models.deletion
import payments.models
import uuid
from decimal import Decimal
from django.db import migrations, models


def create_wallets_and_linked_accounts(apps, schema_editor):
    Customer = apps.get_model('payments', 'Customer')
    Merchant = apps.get_model('payments', 'Merchant')
    Wallet = apps.get_model('payments', 'Wallet')
    LinkedAccount = apps.get_model('payments', 'LinkedAccount')
    DebitMandate = apps.get_model('payments', 'DebitMandate')
    LinkedMoMoAccount = apps.get_model('payments', 'LinkedMoMoAccount')

    bank_names = {
        'fnb': 'FNB Eswatini', 'standard': 'Standard Bank',
        'nedbank': 'Nedbank', 'eswatini_bank': 'Eswatini Bank',
    }
    for customer in Customer.objects.all():
        Wallet.objects.get_or_create(customer=customer)
        first_account = None
        for mandate in DebitMandate.objects.filter(customer=customer, status='active'):
            digits = ''.join(filter(str.isdigit, mandate.account_number or ''))
            account = LinkedAccount.objects.create(
                customer=customer,
                account_type='bank',
                provider=mandate.bank,
                display_name=bank_names.get(mandate.bank, mandate.bank.title()),
                account_last4=(digits[-4:] if len(digits) >= 4 else '0000'),
                provider_reference=str(mandate.id),
                routing_key=uuid.uuid4().hex[:8],
                can_debit=True,
                can_credit=True,
            )
            first_account = first_account or account
        momo = LinkedMoMoAccount.objects.filter(customer=customer, status='active').first()
        if momo:
            digits = ''.join(filter(str.isdigit, momo.msisdn))
            account = LinkedAccount.objects.create(
                customer=customer,
                account_type='momo',
                provider='mtn_momo',
                display_name='MTN MoMo',
                account_last4=digits[-4:],
                provider_reference=str(momo.id),
                routing_key=uuid.uuid4().hex[:8],
                can_debit=True,
                can_credit=True,
            )
            first_account = first_account or account
        if first_account and customer.default_funding_mode in ('bank', 'jit'):
            customer.default_payment_source = 'linked'
            customer.default_payment_account = first_account
            customer.save(update_fields=['default_payment_source', 'default_payment_account'])

    for merchant in Merchant.objects.all():
        Wallet.objects.get_or_create(merchant=merchant)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_customerdevicesecret_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_payment_source',
            field=models.CharField(choices=[('wallet', 'Qinance Wallet'), ('credit', 'Qinance Credit'), ('linked', 'Linked Account')], default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='default_settlement_destination',
            field=models.CharField(choices=[('wallet', 'Qinance Wallet'), ('linked', 'Linked Account')], default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='payment_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='settlement_destination',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pendingsettlement',
            name='payment_source',
            field=models.CharField(default='linked', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingsettlement',
            name='settlement_destination',
            field=models.CharField(default='wallet', max_length=20),
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('momo', 'MTN MoMo')], default='bank', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('account_last4', models.CharField(max_length=4)),
                ('provider_reference', models.CharField(blank=True, max_length=150)),
                ('routing_key', models.CharField(default=payments.models.generate_routing_key, editable=False, max_length=8, unique=True)),
                ('can_debit', models.BooleanField(default=True)),
                ('can_credit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='payments.customer')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='payments.merchant')),
            ],
            options={
                'ordering': ['display_name', 'account_last4'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_settlements', to='payments.merchant')),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.linkedaccount')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='default_payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_defaults', to='payments.linkedaccount'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='default_settlement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_defaults', to='payments.linkedaccount'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='payment_source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions_as_source', to='payments.linkedaccount'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='settlement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions_as_destination', to='payments.linkedaccount'),
        ),
        migrations.AddField(
            model_name='pendingsettlement',
            name='payment_source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_settlements_as_source', to='payments.linkedaccount'),
        ),
        migrations.AddField(
            model_name='pendingsettlement',
            name='settlement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_settlements_as_destination', to='payments.linkedaccount'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='SZL', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='payments.customer')),
                ('merchant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('topup', 'Top up'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('settlement', 'External settlement'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=150)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_wallets_and_linked_accounts, noop_reverse),
        migrations.AddConstraint(
            model_name='linkedaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('merchant__isnull', True)), models.Q(('customer__isnull', True), ('merchant__isnull', False)), _connector='OR'), name='linked_account_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('merchant__isnull', True)), models.Q(('customer__isnull', True), ('merchant__isnull', False)), _connector='OR'), name='wallet_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_non_negative_balance'),
        ),
    ]
