# Generated by Django 5.1.4 on 2026-07-02 11:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_merchant_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], default='weekly', max_length=12),
        ),
    ]
