# Generated by Django 5.1.4 on 2026-08-08 08:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_merchantloan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
