# Generated by Django 5.1.4 on 2026-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_merchant_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
