# Generated by Django 5.1.4 on 2026-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_merchant_description_merchant_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
