# Generated by Django 5.1.4 on 2026-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_merchant_latitude_merchant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantloan',
            name='term_months',
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='duration_days',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='loan_type',
            field=models.CharField(choices=[('campaign', 'Campaign Loan'), ('capital', 'Working Capital Loan')], default='capital', max_length=20),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='repayment_schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='repayment_schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='repayment_source',
            field=models.CharField(choices=[('wallet', 'Qinance Wallet'), ('linked', 'Linked Bank Account')], default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='merchantloan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
