# Generated by Django 5.1.4 on 2026-05-11 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_email_alter_user_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Document expiry date — required for ID and passport', null=True),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('credit_bureau_check', 'Credit Bureau Check'), ('marketing_communications', 'Marketing Communications'), ('data_sharing', 'Data Sharing'), ('data_erasure_requested', 'Data Erasure Request')], max_length=40)),
                ('accepted', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
