# Generated by Django 5.1.4 on 2026-06-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login', 'Login'), ('transaction', 'Transaction'), ('password_reset', 'Password Reset'), ('pin_reset', 'PIN Reset')], max_length=30),
        ),
    ]
