# Generated by Django 5.1.4 on 2026-06-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login', 'Login'), ('transaction', 'Transaction'), ('password_reset', 'Password Reset'), ('pin_reset', 'PIN Reset'), ('web_login', 'Web Login')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('support', 'Support'), ('kyc_officer', 'KYC Officer'), ('credit_officer', 'Credit Officer'), ('fraud_analyst', 'Fraud Analyst'), ('super_admin', 'Super Admin')], default='support', max_length=30),
        ),
    ]
