# Generated by Django 5.1.4 on 2026-08-08 08:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0014_merchant_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100)),
                ('user_role', models.CharField(blank=True, default='', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='campaigns_a_feature_d5244d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('deal_type', models.CharField(choices=[('discount', 'Discount'), ('cashback', 'Cashback'), ('bogo', 'Buy One Get One'), ('free_item', 'Free Item'), ('bundle', 'Bundle Offer'), ('limited_time', 'Limited Time Offer'), ('new_customer', 'New Customer Offer'), ('loyalty', 'Loyalty Offer')], default='discount', max_length=20)),
                ('goal', models.CharField(choices=[('increase_customers', 'Increase Customers'), ('increase_sales', 'Increase Sales'), ('reduce_inventory', 'Reduce Inventory'), ('weekend', 'Weekend Promotion'), ('holiday', 'Holiday Promotion'), ('new_product', 'New Product Launch'), ('loyalty', 'Customer Loyalty')], default='increase_customers', max_length=30)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cashback_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_redemptions', models.PositiveIntegerField(default=0)),
                ('redemptions', models.PositiveIntegerField(default=0)),
                ('applicable_products', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_visits', models.PositiveIntegerField(default=0)),
                ('payments', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('avg_basket_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('repeat_customers', models.PositiveIntegerField(default=0)),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('top_products', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_health', models.IntegerField(default=0)),
                ('health_label', models.CharField(blank=True, max_length=30)),
                ('growth_score', models.IntegerField(default=0)),
                ('marketing_score', models.IntegerField(default=0)),
                ('customer_satisfaction', models.IntegerField(default=0)),
                ('repayment_behaviour', models.CharField(blank=True, max_length=30)),
                ('campaign_effectiveness', models.CharField(blank=True, max_length=30)),
                ('revenue_trend', models.CharField(blank=True, max_length=30)),
                ('recommended_actions', models.TextField(blank=True)),
                ('visibility_score', models.IntegerField(default=0)),
                ('segmentation', models.CharField(blank=True, max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteMerchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_merchants', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='payments.merchant')),
            ],
            options={
                'unique_together': {('customer', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='SavedDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='campaigns.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_deals', to='payments.customer')),
            ],
            options={
                'unique_together': {('customer', 'campaign')},
            },
        ),
    ]
