# Generated by Django 5.1.4 on 2026-08-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ailog',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ailog',
            name='response_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ailog',
            name='tool_used',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
